services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    image: guide.backend
    container_name: guide.backend
    entrypoint: /usr/src/app/docker/backend/server-entrypoint.sh
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4
    # command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app/backend
    env_file:
      - .env/.env
      - .env/.env.db
    expose:
      - 8000
    depends_on:
      - db
  
  db:
    image: postgres:16
    container_name: guide.db
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env/.env.db
    expose:
      - 5432

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: guide.nginx
    container_name: guide.nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  db_data: {}
